# Generated by Django 5.2.6 on 2025-10-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
